// Code generated by protoc-gen-go. DO NOT EDIT.
// source: employee.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	employee.proto

It has these top-level messages:
	EmployeeRequest
	EmployeeResponse
	EmployeeFilter
	Employees
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmployeeRequest struct {
	Id        string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Age       int32   `protobuf:"varint,3,opt,name=age" json:"age,omitempty"`
	Address   string  `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	Salary    float64 `protobuf:"fixed64,5,opt,name=salary" json:"salary,omitempty"`
	CreatedAt string  `protobuf:"bytes,6,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt string  `protobuf:"bytes,7,opt,name=updatedAt" json:"updatedAt,omitempty"`
	Version   int32   `protobuf:"varint,8,opt,name=version" json:"version,omitempty"`
}

func (m *EmployeeRequest) Reset()                    { *m = EmployeeRequest{} }
func (m *EmployeeRequest) String() string            { return proto.CompactTextString(m) }
func (*EmployeeRequest) ProtoMessage()               {}
func (*EmployeeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EmployeeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmployeeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EmployeeRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *EmployeeRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EmployeeRequest) GetSalary() float64 {
	if m != nil {
		return m.Salary
	}
	return 0
}

func (m *EmployeeRequest) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *EmployeeRequest) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *EmployeeRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type EmployeeResponse struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *EmployeeResponse) Reset()                    { *m = EmployeeResponse{} }
func (m *EmployeeResponse) String() string            { return proto.CompactTextString(m) }
func (*EmployeeResponse) ProtoMessage()               {}
func (*EmployeeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EmployeeResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmployeeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type EmployeeFilter struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *EmployeeFilter) Reset()                    { *m = EmployeeFilter{} }
func (m *EmployeeFilter) String() string            { return proto.CompactTextString(m) }
func (*EmployeeFilter) ProtoMessage()               {}
func (*EmployeeFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EmployeeFilter) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Employees struct {
	Employees []*EmployeeRequest `protobuf:"bytes,1,rep,name=employees" json:"employees,omitempty"`
}

func (m *Employees) Reset()                    { *m = Employees{} }
func (m *Employees) String() string            { return proto.CompactTextString(m) }
func (*Employees) ProtoMessage()               {}
func (*Employees) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Employees) GetEmployees() []*EmployeeRequest {
	if m != nil {
		return m.Employees
	}
	return nil
}

func init() {
	proto.RegisterType((*EmployeeRequest)(nil), "api.EmployeeRequest")
	proto.RegisterType((*EmployeeResponse)(nil), "api.EmployeeResponse")
	proto.RegisterType((*EmployeeFilter)(nil), "api.EmployeeFilter")
	proto.RegisterType((*Employees)(nil), "api.Employees")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EmployeeService service

type EmployeeServiceClient interface {
	CreateEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	GetEmployee(ctx context.Context, in *EmployeeFilter, opts ...grpc.CallOption) (EmployeeService_GetEmployeeClient, error)
	GetAll(ctx context.Context, in *EmployeeFilter, opts ...grpc.CallOption) (EmployeeService_GetAllClient, error)
}

type employeeServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeServiceClient(cc *grpc.ClientConn) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) CreateEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := grpc.Invoke(ctx, "/api.EmployeeService/CreateEmployee", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) GetEmployee(ctx context.Context, in *EmployeeFilter, opts ...grpc.CallOption) (EmployeeService_GetEmployeeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_EmployeeService_serviceDesc.Streams[0], c.cc, "/api.EmployeeService/GetEmployee", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServiceGetEmployeeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EmployeeService_GetEmployeeClient interface {
	Recv() (*EmployeeRequest, error)
	grpc.ClientStream
}

type employeeServiceGetEmployeeClient struct {
	grpc.ClientStream
}

func (x *employeeServiceGetEmployeeClient) Recv() (*EmployeeRequest, error) {
	m := new(EmployeeRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *employeeServiceClient) GetAll(ctx context.Context, in *EmployeeFilter, opts ...grpc.CallOption) (EmployeeService_GetAllClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_EmployeeService_serviceDesc.Streams[1], c.cc, "/api.EmployeeService/GetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EmployeeService_GetAllClient interface {
	Recv() (*Employees, error)
	grpc.ClientStream
}

type employeeServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *employeeServiceGetAllClient) Recv() (*Employees, error) {
	m := new(Employees)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for EmployeeService service

type EmployeeServiceServer interface {
	CreateEmployee(context.Context, *EmployeeRequest) (*EmployeeResponse, error)
	GetEmployee(*EmployeeFilter, EmployeeService_GetEmployeeServer) error
	GetAll(*EmployeeFilter, EmployeeService_GetAllServer) error
}

func RegisterEmployeeServiceServer(s *grpc.Server, srv EmployeeServiceServer) {
	s.RegisterService(&_EmployeeService_serviceDesc, srv)
}

func _EmployeeService_CreateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).CreateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EmployeeService/CreateEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).CreateEmployee(ctx, req.(*EmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_GetEmployee_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmployeeFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmployeeServiceServer).GetEmployee(m, &employeeServiceGetEmployeeServer{stream})
}

type EmployeeService_GetEmployeeServer interface {
	Send(*EmployeeRequest) error
	grpc.ServerStream
}

type employeeServiceGetEmployeeServer struct {
	grpc.ServerStream
}

func (x *employeeServiceGetEmployeeServer) Send(m *EmployeeRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _EmployeeService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmployeeFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmployeeServiceServer).GetAll(m, &employeeServiceGetAllServer{stream})
}

type EmployeeService_GetAllServer interface {
	Send(*Employees) error
	grpc.ServerStream
}

type employeeServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *employeeServiceGetAllServer) Send(m *Employees) error {
	return x.ServerStream.SendMsg(m)
}

var _EmployeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEmployee",
			Handler:    _EmployeeService_CreateEmployee_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEmployee",
			Handler:       _EmployeeService_GetEmployee_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAll",
			Handler:       _EmployeeService_GetAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "employee.proto",
}

func init() { proto.RegisterFile("employee.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xdd, 0x6a, 0xc2, 0x30,
	0x14, 0x36, 0x56, 0xab, 0x3d, 0x42, 0x27, 0xd9, 0x0f, 0x41, 0x76, 0x51, 0x72, 0xd5, 0x2b, 0xd9,
	0xdc, 0xad, 0x20, 0x32, 0x36, 0xef, 0xbb, 0x27, 0xc8, 0xda, 0xc3, 0x08, 0xab, 0xb6, 0x4b, 0xa2,
	0xe0, 0xf3, 0xed, 0x01, 0xf6, 0x4a, 0x23, 0xb1, 0xd1, 0xe9, 0x7a, 0x77, 0xbe, 0xbf, 0xf4, 0x7c,
	0x87, 0x42, 0x8c, 0xeb, 0xba, 0xac, 0xf6, 0x88, 0xd3, 0x5a, 0x55, 0xa6, 0xa2, 0x81, 0xa8, 0x25,
	0xff, 0x21, 0x70, 0xf5, 0xd2, 0xf0, 0x19, 0x7e, 0x6d, 0x51, 0x1b, 0x1a, 0x43, 0x57, 0x16, 0x8c,
	0x24, 0x24, 0x8d, 0xb2, 0xae, 0x2c, 0x28, 0x85, 0xde, 0x46, 0xac, 0x91, 0x75, 0x1d, 0xe3, 0x66,
	0x3a, 0x86, 0x40, 0x7c, 0x20, 0x0b, 0x12, 0x92, 0xf6, 0x33, 0x3b, 0x52, 0x06, 0x03, 0x51, 0x14,
	0x0a, 0xb5, 0x66, 0x3d, 0x67, 0xf4, 0x90, 0xde, 0x41, 0xa8, 0x45, 0x29, 0xd4, 0x9e, 0xf5, 0x13,
	0x92, 0x92, 0xac, 0x41, 0xf4, 0x1e, 0xa2, 0x5c, 0xa1, 0x30, 0x58, 0x2c, 0x0d, 0x0b, 0x5d, 0xe6,
	0x44, 0x58, 0x75, 0x5b, 0x17, 0x8d, 0x3a, 0x38, 0xa8, 0x47, 0xc2, 0x7e, 0x6d, 0x87, 0x4a, 0xcb,
	0x6a, 0xc3, 0x86, 0x6e, 0x07, 0x0f, 0xf9, 0x1c, 0xc6, 0xa7, 0x42, 0xba, 0xae, 0x36, 0x1a, 0xff,
	0x35, 0x62, 0x30, 0xd0, 0xdb, 0x3c, 0xb7, 0xbb, 0xda, 0x52, 0xc3, 0xcc, 0x43, 0xce, 0x21, 0xf6,
	0xe9, 0x57, 0x59, 0x1a, 0x54, 0xb6, 0xe9, 0x27, 0xee, 0x9b, 0xb0, 0x1d, 0xf9, 0x02, 0x22, 0xef,
	0xd1, 0x74, 0x06, 0x91, 0xbf, 0xab, 0x66, 0x24, 0x09, 0xd2, 0xd1, 0xec, 0x66, 0x2a, 0x6a, 0x39,
	0xbd, 0xb8, 0x6a, 0x76, 0xb2, 0xcd, 0xbe, 0xff, 0x1c, 0xfd, 0x0d, 0xd5, 0x4e, 0xe6, 0x48, 0x17,
	0x10, 0x3f, 0xbb, 0xee, 0x5e, 0xa0, 0xad, 0xcf, 0x4c, 0x6e, 0x2f, 0xd8, 0x43, 0x43, 0xde, 0xa1,
	0x73, 0x18, 0xad, 0xd0, 0x1c, 0xd3, 0xd7, 0x67, 0xbe, 0x43, 0x97, 0x49, 0xeb, 0x93, 0xbc, 0xf3,
	0x40, 0xe8, 0x23, 0x84, 0x2b, 0x34, 0xcb, 0xb2, 0x6c, 0x0f, 0xc6, 0x67, 0xa4, 0xb6, 0x91, 0xf7,
	0xd0, 0xfd, 0x46, 0x4f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x6c, 0x23, 0x1e, 0x58, 0x02,
	0x00, 0x00,
}
